# run parameters
DATA_ROOT="/data/redpajama_tests"
ARTIFACTS_ID="rpv2"
INPUT_BASE_URI="file://${DATA_ROOT}/"
OUTPUT_BASE_URI="file://${DATA_ROOT}/rpv2"
MAX_DOCS=100
LANGUAGES=("uk")

# filename keep filters
FILENAME_KEEP_PATTERNS=(
".*/[a-z]{2}_middle\.json\.gz"
".*/[a-z]{2}_head\.json\.gz"
)

# General parameters used across steps
S3_ENDPOINT_URL=""
S3_BUCKET=""
S3_CCNET_PREFIX="/rs_cc_net"
S3_PROFILE=""

# Docker
DOCKER_S3_ENDPOINT_URL=""
DOCKER_MNT_DIR="/data/redpajama_tests/"
DOCKER_REPO=""

# Dedupe
MINHASH_NGRAM_SIZE="13"
MINHASH_NUM_PERMUTATIONS="128"
MINHASH_SIMILARITIES=(1.0 0.9 0.8 0.7)

# DSIR
DSIR_NUM_SAMPLES=500000
DSIR_FEATURE_DIM=10000

# Classifiers
CLASSIFIERS_NUM_SAMPLES=75000

# sampling for books artifacts
MAX_SAMPLES_PER_BOOK=1000
MAX_PARAGRAPHS_PER_BOOK_SAMPLE=250

# Others
INPUTS_PER_PROCESS=20 # the number of files processed by one process at a time

# domain blacklist categories
DOMAIN_BLACKLIST_CATEGORIES=(
"adult"
"agressive"
"agressif"
"arjel"
"chat"
"dating"
"ddos"
"filehosting"
"gambling"
"porn"
"mixed_adult"
"phishing"
"violence"
)

# CC snapshot ids to process
CC_SNAPSHOT_IDS=()

LOCAL_BAD_WORDS_DIR="app/bad_words/"